---
- hosts: all
  become: true

  tasks:
    - name: stop previous version docker
      shell: docker stop mini-project
    - name: remove stopped container
      shell: docker rm -f mini-project
    - name: remove docker images
      shell: docker image rm -f lasya1999/mini-project:latest

    - name: create docker image
      shell: docker run -d -p 80:80 --name mini-project lasya1999/mini-project:latest
